WITH ColumnMap AS (
    SELECT 'StateCode_BL01' AS ColumnName, 'BL01' AS NBI_Id
    UNION ALL SELECT 'BridgeNo_BID01', 'BID01'
    UNION ALL SELECT 'BridgeName_BID02', 'BID02'
    UNION ALL SELECT 'PrevBridgeNo_BID03', 'BID03'
    UNION ALL SELECT 'CountyCode_BL02', 'BL02'
    UNION ALL SELECT 'PlaceCode_BL03', 'BL03'
    UNION ALL SELECT 'HighwayDist_BL04', 'BL04'
    UNION ALL SELECT 'Latitude_BL05', 'BL05'
    UNION ALL SELECT 'Longitude_BL06', 'BL06'
    UNION ALL SELECT 'BorderBridgeNo_BL07', 'BL07'
    UNION ALL SELECT 'BorderBridgeStateCode_BL08', 'BL08'
    UNION ALL SELECT 'BorderBridgeInspectResp_BL09', 'BL09'
    UNION ALL SELECT 'BorderBridgeLeadState_BL10', 'BL10'
    UNION ALL SELECT 'BridgeLocation_BL11', 'BL11'
    UNION ALL SELECT 'MPO_BL12', 'BL12'
    UNION ALL SELECT 'Owner_BCL01', 'BCL01'
    UNION ALL SELECT 'MaintResp_BCL02', 'BCL02'
    UNION ALL SELECT 'FedTribalAccess_BCL03', 'BCL03'
    UNION ALL SELECT 'HistSignificance_BCL04', 'BCL04'
    UNION ALL SELECT 'Toll_BCL05', 'BCL05'
    UNION ALL SELECT 'EmergencyEvacDesig_BCL06', 'BCL06'
    UNION ALL SELECT 'BridgeRailings_BRH01', 'BRH01'
    UNION ALL SELECT 'Transitions_BRH02', 'BRH02'
    UNION ALL SELECT 'NBISBridgeLength_BG01', 'BG01'
    UNION ALL SELECT 'TotalBridgeLength_BG02', 'BG02'
    UNION ALL SELECT 'MaxSpanLength_BG03', 'BG03'
    UNION ALL SELECT 'MinSpanLength_BG04', 'BG04'
    UNION ALL SELECT 'BridgeWidthOut_BG05', 'BG05'
    UNION ALL SELECT 'BridgeWidthCurb_BG06', 'BG06'
    UNION ALL SELECT 'LeftCurbWidth_BG07', 'BG07'
    UNION ALL SELECT 'RightCurbWidth_BG08', 'BG08'
    UNION ALL SELECT 'ApproachRoadwayWidth_BG09', 'BG09'
    UNION ALL SELECT 'BridgeMedian_BG10', 'BG10'
    UNION ALL SELECT 'Skew_BG11', 'BG11'
    UNION ALL SELECT 'CurvedBridge_BG12', 'BG12'
    UNION ALL SELECT 'MaxBridgeHeight_BG13', 'BG13'
    UNION ALL SELECT 'SidehillBridge_BG14', 'BG14'
    UNION ALL SELECT 'IrregularDeckArea_BG15', 'BG15'
    UNION ALL SELECT 'CalculatedDeckArea_BG16', 'BG16'
    UNION ALL SELECT 'DesignLoad_BLR01', 'BLR01'
    UNION ALL SELECT 'DesignMethod_BLR02', 'BLR02'
    UNION ALL SELECT 'LoadRatingDate_BLR03', 'BLR03'
    UNION ALL SELECT 'LoadRatingMethod_BLR04', 'BLR04'
    UNION ALL SELECT 'InventoryLRFactor_BLR05', 'BLR05'
    UNION ALL SELECT 'OperatingLRFactor_BLR06', 'BLR06'
    UNION ALL SELECT 'ControllingLegalLRFactor_BLR07', 'BLR07'
    UNION ALL SELECT 'RoutinePermitLoads_BLR08', 'BLR08'
    UNION ALL SELECT 'NSTMInspectReq_BIR01', 'BIR01'
    UNION ALL SELECT 'FatigueDetails_BIR02', 'BIR02'
    UNION ALL SELECT 'UnderwaterInspectReq_BIR03', 'BIR03'
    UNION ALL SELECT 'ComplexFeature_BIR04', 'BIR04'
    UNION ALL SELECT 'DeckCondRate_BC01', 'BC01'
    UNION ALL SELECT 'SuperstrCondRate_BC02', 'BC02'
    UNION ALL SELECT 'SubstructCondRate_BC03', 'BC03'
    UNION ALL SELECT 'CulvertCondRate_BC04', 'BC04'
    UNION ALL SELECT 'BridgeRailCondRate_BC05', 'BC05'
    UNION ALL SELECT 'BridgeRailTransitCondRate_BC06', 'BC06'
    UNION ALL SELECT 'BridgeBearingCondRate_BC07', 'BC07'
    UNION ALL SELECT 'BridgeJointCondRate_BC08', 'BC08'
    UNION ALL SELECT 'ChannelCondRate_BC09', 'BC09'
    UNION ALL SELECT 'ChannelProtectCondRate_BC10', 'BC10'
    UNION ALL SELECT 'ScourCondRate_BC11', 'BC11'
    UNION ALL SELECT 'BridgeCondClass_BC12', 'BC12'
    UNION ALL SELECT 'LowestCondRateCode_BC13', 'BC13'
    UNION ALL SELECT 'ApproachRoadwayAlign_BAP01', 'BAP01'
    UNION ALL SELECT 'OvertopLikelihood_BAP02', 'BAP02'
    UNION ALL SELECT 'ScourVulnerability_BAP03', 'BAP03'
    UNION ALL SELECT 'ScourPlanOfAction_BAP04', 'BAP04'
    UNION ALL SELECT 'SeismicVulnerability_BAP05', 'BAP05'
    UNION ALL SELECT 'YearBuilt_W1', 'W01'
    UNION ALL SELECT 'ElementNo_BE01', 'BE01'
    UNION ALL SELECT 'ElementParentNo_BE02', 'BE02'
    UNION ALL SELECT 'ElementTotalQuantity_BE03', 'BE03'
    UNION ALL SELECT 'ElementCS1_BCS01', 'BCS01'
    UNION ALL SELECT 'ElementCS2_BCS02', 'BCS02'
    UNION ALL SELECT 'ElementCS3_BCS03', 'BCS03'
    UNION ALL SELECT 'ElementCS4_BCS04', 'BCS04'
    UNION ALL SELECT 'FeatureType_BF01', 'BF01'
    UNION ALL SELECT 'FeatureLocation_BF02', 'BF02'
    UNION ALL SELECT 'FeatureName_BF03', 'BF03'
    UNION ALL SELECT 'FuncClass_BH01', 'BH01'
    UNION ALL SELECT 'UrbanCode_BH02', 'BH02'
    UNION ALL SELECT 'NHSDesig_BH03', 'BH03'
    UNION ALL SELECT 'NatHwyFreightNet_BH04', 'BH04'
    UNION ALL SELECT 'STRAHNETDesig_BH05', 'BH05'
    UNION ALL SELECT 'LRSRouteID_BH06', 'BH06'
    UNION ALL SELECT 'LRSMilePoint_BH07', 'BH07'
    UNION ALL SELECT 'LanesOnHwy_BH08', 'BH08'
    UNION ALL SELECT 'AADT_BH09', 'BH09'
    UNION ALL SELECT 'AADTT_BH10', 'BH10'
    UNION ALL SELECT 'YearAADT_BH11', 'BH11'
    UNION ALL SELECT 'HwyMaxVertClearance_BH12', 'BH12'
    UNION ALL SELECT 'HwyMinVertClearance_BH13', 'BH13'
    UNION ALL SELECT 'HwyMinHorizClearanceLeft_BH14', 'BH14'
    UNION ALL SELECT 'HwyMinHorizClearanceRight_BH15', 'BH15'
    UNION ALL SELECT 'HwyMaxUsableSurfaceWidth_BH16', 'BH16'
    UNION ALL SELECT 'BypassDetourLength_BH17', 'BH17'
    UNION ALL SELECT 'CrossingBridgeNo_BH18', 'BH18'
    UNION ALL SELECT 'RailroadServiceType_BRR01', 'BRR01'
    UNION ALL SELECT 'RailroadMinVertClearance_BRR02', 'BRR02'
    UNION ALL SELECT 'RailroadMinHorizOffset_BRR03', 'BRR03'
    UNION ALL SELECT 'NavWaterway_BN01', 'BN01'
    UNION ALL SELECT 'NavMinVertClearance_BN02', 'BN02'
    UNION ALL SELECT 'MovableMaxNavVertClearance_BN03', 'BN03'
    UNION ALL SELECT 'NavChannelWidth_BN04', 'BN04'
    UNION ALL SELECT 'NavChannelMinHorizClearance_BN05', 'BN05'
    UNION ALL SELECT 'SubstructNavProtection_BN06', 'BN06'
    UNION ALL SELECT 'InspectionType_BIE01', 'BIE01'
    UNION ALL SELECT 'BeginDate_BIE02', 'BIE02'
    UNION ALL SELECT 'CompletionDate_BIE03', 'BIE03'
    UNION ALL SELECT 'NC_BridgeInspector_BIE04', 'BIE04'
    UNION ALL SELECT 'InspectInterval_BIE05', 'BIE05'
    UNION ALL SELECT 'InspectDueDate_BIE06', 'BIE06'
    UNION ALL SELECT 'RBI_Method_BIE07', 'BIE07'
    UNION ALL SELECT 'QltyControlDate_BIE08', 'BIE08'
    UNION ALL SELECT 'QltyAssuranceDate_BIE09', 'BIE09'
    UNION ALL SELECT 'InspectDataUpdateDate_BIE10', 'BIE10'
    UNION ALL SELECT 'InspectionNote_BIE11', 'BIE11'
    UNION ALL SELECT 'LegalLoadConfig_BEP01', 'BEP01'
    UNION ALL SELECT 'LegalLoadRatingFactor_BEP02', 'BEP02'
    UNION ALL SELECT 'PostingType_BEP03', 'BEP03'
    UNION ALL SELECT 'PostingValue_BEP04', 'BEP04'
    UNION ALL SELECT 'PostingStatusChangeDate_BPS02', 'BPS02'
    UNION ALL SELECT 'LoadPostingStatus_BPS01', 'BPS01'
    UNION ALL SELECT 'RouteDesignation_BRT01', 'BRT01'
    UNION ALL SELECT 'RouteNumber_BRT02', 'BRT02'
    UNION ALL SELECT 'RouteDirection_BRT03', 'BRT03'
    UNION ALL SELECT 'RouteType_BRT04', 'BRT04'
    UNION ALL SELECT 'ServiceType_BRT05', 'BRT05'
    UNION ALL SELECT 'SpanConfigDesig_BSP01', 'BSP01'
    UNION ALL SELECT 'NumberOfSpans_BSP02', 'BSP02'
    UNION ALL SELECT 'NumberOfBeamLines_BSP03', 'BSP03'
    UNION ALL SELECT 'SpanMaterial_BSP04', 'BSP04'
    UNION ALL SELECT 'SpanContinuity_BSP05', 'BSP05'
    UNION ALL SELECT 'SpanType_BSP06', 'BSP06'
    UNION ALL SELECT 'SpanProtectSystem_BSP07', 'BSP07'
    UNION ALL SELECT 'DeckInteraction_BSP08', 'BSP08'
    UNION ALL SELECT 'DeckMaterial_BSP09', 'BSP09'
    UNION ALL SELECT 'WearingSurface_BSP10', 'BSP10'
    UNION ALL SELECT 'DeckProtectSystem_BSP11', 'BSP11'
    UNION ALL SELECT 'DeckReinforcSystem_BSP12', 'BSP12'
    UNION ALL SELECT 'DeckStayInPlaceForms_BSP13', 'BSP13'
    UNION ALL SELECT 'SubstructConfigDesig_BSB01', 'BSB01'
    UNION ALL SELECT 'NoSubstructUnits_BSB02', 'BSB02'
    UNION ALL SELECT 'SubstructMaterial_BSB03', 'BSB03'
    UNION ALL SELECT 'SubstructType_BSB04', 'BSB04'
    UNION ALL SELECT 'SubstructProtectSystem_BSB05', 'BSB05'
    UNION ALL SELECT 'FoundationType_BSB06', 'BSB06'
    UNION ALL SELECT 'FoundationProtectSystem_BSB07', 'BSB07'
    UNION ALL SELECT 'YearWorkPerformed_BW02', 'BW02'
    UNION ALL SELECT 'WorkPerformed_BW03', 'BW03'

)

-- Update Lookup_DataItems.Identifier with the column name
UPDATE L
SET L.Identifier = C.ColumnName
FROM [NBI].[Lookup_DataItems] L
JOIN ColumnMap C ON L.NBI_Id = C.NBI_Id;









